#!/usr/bin/env node
// Assemble docs/demo/ — the static browser demo of the dashboard, published at
// xenon-app.com/demo so a shared link is a product trial instead of a download
// page. See docs/ROADMAP-REACH.md, phase R0.
//
// WHY THIS RUNS IN CI AND IS NEVER COMMITTED
// The output is ~8 MB of copied client assets. `self-update.js` downloads
// GitHub's tag SOURCE zip and `update-apply.ps1` robocopies it into every user's
// install root, so anything tracked here would land on every user's disk and
// more than double a ~6 MB release. It is git-ignored, generated by
// .github/workflows/pages.yml immediately before the Pages upload, and
// export-ignored as well in case someone ever `git add -f`s it.
//
// WHY IT PATCHES ALMOST NOTHING
// Exactly ONE source file is rewritten: server/js/state.js. Its `SERVER` const
// lives in the script-global lexical environment of a classic script — it is not
// a property of window (so it cannot be reassigned) and a second `const SERVER`
// is a SyntaxError that would kill the script. Every other behavioural change is
// an override installed at runtime by demo/boot.js. Keep it that way: the more
// this script rewrites, the more it silently rots against server/js/**.
//
// NOTE FOR ANYONE HARDENING THIS LATER: do not add a CSP. server/index.html
// carries ~200 inline onclick= handlers, so any policy without 'unsafe-inline'
// bricks the page — and gating those buttons individually is impossible, which
// is precisely why every destructive path is stopped at the network boundary in
// demo/boot.js instead.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, statSync, readdirSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'demo');

const log = (msg) => process.stdout.write('[build-demo] ' + msg + '\n');
function fail(msg) {
  process.stderr.write('build-demo: ' + msg + '\n');
  process.exit(1);
}

// The copy allowlist is not invented: it IS the directory list in the server's
// own static route. Whatever the server serves, the demo must serve.
// server/test/demo-build.test.mjs pins the two together, so a new served
// directory can never silently 404 here.
export const COPY_ALLOWLIST = ['js', 'components', 'styles', 'vendor', 'public', 'assets'];

// Every anchor is asserted to occur exactly once in its source. A rename
// upstream fails the build loudly instead of producing a demo that boots into
// something subtly wrong.
function patchOnce(src, anchor, replacement, what) {
  const parts = src.split(anchor);
  if (parts.length !== 2) fail(`anchor for "${what}" occurs ${parts.length - 1} times, expected exactly 1`);
  log('  ✓ ' + what);
  return parts[0] + replacement + parts[1];
}

function cutOnce(src, startAnchor, endAnchor, what) {
  const a = src.indexOf(startAnchor);
  if (a < 0 || src.indexOf(startAnchor, a + 1) >= 0) fail(`start anchor for "${what}" is not unique`);
  const b = src.indexOf(endAnchor, a);
  if (b < 0) fail(`end anchor for "${what}" not found after its start`);
  log('  ✓ ' + what + ' (removed)');
  return src.slice(0, a) + src.slice(b + endAnchor.length);
}

function dirSize(dir) {
  let total = 0;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    total += st.isDirectory() ? dirSize(p) : st.size;
  }
  return total;
}

// ── 0. Always build from scratch. Idempotence is structural, not defensive:
//      there is no "already patched" state in the output to detect.
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
const stamp = new Date().toISOString();
log(`building v${version} → docs/demo`);

// ── 1. Copy the client assets.
for (const rel of COPY_ALLOWLIST) {
  const from = join(ROOT, 'server', rel);
  if (!existsSync(from)) fail(`server/${rel} is missing — the copy allowlist is out of date`);
  cpSync(from, join(OUT, rel), { recursive: true });
}
log('copied ' + COPY_ALLOWLIST.join(', '));

// Drop the 1.12 MB hi-res logo; patch 6 below rewrites its only reference to the
// 28 KB mark. One PNG was 14% of the whole payload and it is incompressible.
rmSync(join(OUT, 'public', 'images', 'logo', 'logo.png'), { force: true });

// ── 2. Materialize shared/ from packages/core — NEVER from server/shared.
//      That path is a junction on Windows and a `dir` symlink elsewhere
//      (tools/link-shared.mjs), and cpSync without dereference copies the LINK,
//      producing a dangling docs/demo/shared on Pages: every module then quietly
//      takes its inline fallback and nothing looks broken until it is.
const CORE_SRC = join(ROOT, 'packages', 'core', 'src');
if (!existsSync(CORE_SRC)) fail('packages/core/src is missing — cannot materialize shared/');
cpSync(CORE_SRC, join(OUT, 'shared', 'src'), { recursive: true });
if (existsSync(join(ROOT, 'server', 'shared'))) log('  (server/shared exists and is deliberately ignored — see above)');
log('materialized shared/src from packages/core');

// ── 3. The one source patch: SERVER.
{
  const file = join(OUT, 'js', 'state.js');
  const anchor = "const SERVER = (typeof window !== 'undefined' && window.location &&";
  // Prefix-insert rather than rewrite, so this survives any future edit to the
  // hostname list below it. '' (not location.origin) makes every SERVER + '/x'
  // call take the same shape as the ~116 raw fetch('/x') sites, which leaves the
  // shim with exactly one normalization rule.
  const src = readFileSync(file, 'utf8');
  writeFileSync(file, patchOnce(src, anchor,
    "const SERVER = '';   /* xenon-demo: static build — every request is same-origin and shimmed */\n"
    + 'const _XENON_DEMO_SERVER_ORIG = ' + anchor.replace('const SERVER = ', ''),
    'js/state.js SERVER → same-origin'));
}

// ── 4. index.html.
{
  let html = readFileSync(join(ROOT, 'server', 'index.html'), 'utf8');

  // 4a. The site's analytics + consent prelude, EXTRACTED from docs/index.html
  //     rather than duplicated, so the demo's consent posture can never drift
  //     from the rest of the site.
  const site = readFileSync(join(ROOT, 'docs', 'index.html'), 'utf8');
  const preStart = site.indexOf('<!-- Google tag (gtag.js) with Consent Mode v2.');
  const beacon = site.indexOf('static.cloudflareinsights.com');
  if (preStart < 0 || beacon < 0) fail('could not locate the analytics prelude in docs/index.html');
  const preEnd = site.indexOf('</script>', beacon);
  if (preEnd < 0) fail('unterminated Cloudflare beacon tag in docs/index.html');
  const prelude = site.slice(preStart, preEnd + '</script>'.length);
  html = patchOnce(html, '<meta charset="UTF-8">',
    '<meta charset="UTF-8">\n' + prelude, 'analytics + consent prelude');

  // 4b. Boot scripts FIRST. settings.js reads localStorage synchronously at
  //     script-evaluation time and several modules probe location.hash on the
  //     way up, so the shims and the seed must already exist.
  html = patchOnce(html, '<script src="shared/src/constants.js"></script>',
    `<script src="demo/data.js?v=${version}"></script>\n`
    + `<script src="demo/boot.js?v=${version}"></script>\n`
    + '<script src="shared/src/constants.js"></script>',
    'demo boot scripts before shared/src/constants.js');

  // 4c. The UI layer LAST, so the fake EventSource main.js created is already
  //     registered and the grid has mounted.
  html = patchOnce(html, '<script src="js/main.js"></script>',
    '<script src="js/main.js"></script>\n'
    + `<link rel="stylesheet" href="demo/demo.css?v=${version}">\n`
    + `<script src="demo/demo.js?v=${version}"></script>`,
    'demo UI layer after js/main.js');

  // 4d. Remove the Xeneon Edge fractional-DPR block. It applies CSS zoom to
  //     <html>, is iCUE-iframe-specific, cannot help a browser tab, and would
  //     scale the demo badge with it.
  html = cutOnce(html, '<!-- EXPERIMENTAL — Xeneon Edge fractional-DPR zoom compensation.',
    '</script>', 'Edge fractional-DPR block');

  // 4e. Head metadata. <html lang> is left alone: i18n.js sets it from the
  //     seeded language.
  html = patchOnce(html, '<title>', '<link rel="canonical" href="https://xenon-app.com/demo/">\n'
    + '<meta name="description" content="Try Xenon in your browser — the full dashboard, running on simulated data. No download.">\n'
    + '<meta name="theme-color" content="#070808">\n'
    + '<meta property="og:title" content="Xenon — try the dashboard in your browser">\n'
    + '<meta property="og:description" content="The full Xenon dashboard, live in your browser on simulated data.">\n'
    + '<meta property="og:url" content="https://xenon-app.com/demo/">\n'
    + '<meta property="og:type" content="website">\n'
    + '<title>', 'head metadata');
  html = html.replace(/<title>[^<]*<\/title>/, '<title>Xenon — try the dashboard in your browser</title>');

  writeFileSync(join(OUT, 'index.html'), html);
  log('wrote index.html');
}

// ── 5. Patch 6: the 1.12 MB logo reference.
{
  const file = join(OUT, 'components', 'SettingsModal', 'SettingsModal.css');
  const src = readFileSync(file, 'utf8');
  writeFileSync(file, patchOnce(src, '/public/images/logo/logo.png', '/public/images/logo/logo-mark.png',
    'SettingsModal.css logo.png → logo-mark.png (−1.1 MB)'));
}

// ── 6. The demo runtime, token-substituted.
{
  const dst = join(OUT, 'demo');
  mkdirSync(dst, { recursive: true });
  for (const name of ['data.js', 'boot.js', 'demo.js', 'demo.css']) {
    const src = readFileSync(join(ROOT, 'tools', 'demo', name), 'utf8');
    writeFileSync(join(dst, name), src.split('__V__').join(version).split('__BUILD__').join(stamp));
  }
  log('wrote demo/ runtime');
}

// ── 7. A #try=<id> fragment must never contain the substring "edge":
//      edge-preview.js tests `hash.indexOf('edge') >= 0` and would silently boot
//      the demo into the 2560x720 letterbox. boot.js strips the fragment before
//      anything reads it, and this is the belt to that pair of braces.
{
  const catalog = JSON.parse(readFileSync(join(ROOT, 'docs', 'community', 'catalog.json'), 'utf8'));
  const bad = (catalog.entries || []).map((e) => e && e.id).filter((id) => id && /edge/i.test(id));
  if (bad.length) fail('catalog ids containing "edge" would trip the Edge-preview hash sniff: ' + bad.join(', '));
}

// ── 8. Build stamp. demo/boot.js reseeds a visitor's localStorage when this
//      changes, so a redeploy repairs anyone left holding corrupted demo state.
writeFileSync(join(OUT, '.build-stamp'), JSON.stringify({ version, builtAt: stamp }, null, 2) + '\n');

log('done — ' + (dirSize(OUT) / (1024 * 1024)).toFixed(1) + ' MB in docs' + sep + 'demo');
